benchmark:
  success_thresholds:
    flat: 0.95
    moderate: 0.92
    steep: 0.85
tool:
  additional_args:
  - --verbose
  environment_variables:
    FLOWFINDER_CACHE_DIR: /tmp/flowfinder_cache
  executable: flowfinder
  timeout_seconds: 120
