benchmark:
  output_formats:
    json: true
    csv: true
    summary: true
    errors: true
  timeout_seconds: 300
logging:
  level: WARNING
performance:
  max_workers: 8
  memory_limit_gb: 16
  parallel_processing: true
